-- Generated by nwg-displays on 2026-06-03 at 01:38:37. Do not edit manually.

hl.monitor({
	output = "eDP-2",
	mode = "1920x1080@144.0",
	position = "0x0",
	scale = 0.9999999999999997,
})
hl.monitor({
	output = "HDMI-A-1",
	mode = "2560x1440@143.91",
	position = "1920x0",
	scale = 1.0,
})
