-- Generated by nwg-displays on 2026-06-03 at 01:39:13. Do not edit manually.

hl.workspace_rule({
	workspace = "1",
	monitor = "eDP-2",
	default = true,
})
hl.workspace_rule({
	workspace = "2",
	monitor = "HDMI-A-1",
	default = true,
})
